Repository OBELISK-TEAM/OBELISK, pull requests merged in 2024-04, with the labels that each got.

#2 feat(githooks)[OK-11] Add git hook
  githooks/prepare-commit-msg
Labels: technical

#3 feat(backend-init)[OK-23] Initialize backend
  README.md
  backend/.gitignore
  backend/.prettierrc
  backend/README.md
  backend/nest-cli.json
  backend/package-lock.json
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/main.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  backend/tsconfig.build.json
  backend/tsconfig.json
Labels: technical, backend

#5 ci(github)[OK-10] Add CI
  .githooks/prepare-commit-msg
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  backend/.eslintrc.js
  backend/package-lock.json
  backend/package.json
  backend/src/main.ts
Labels: technical, CI

#6 ci(github)[OK-31] Change pipelines names to more descriptive
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
Labels: technical, CI
