Repository OBELISK-TEAM/OBELISK, pull requests merged in 2024-10, with the labels that each got.

#97 feat(stats)[OK-174] Add base stats module
  server/src/app.module.ts
  server/src/modules/stats/boards/boards.stats.controller.ts
  server/src/modules/stats/boards/boards.stats.module.ts
  server/src/modules/stats/boards/boards.stats.service.ts
  server/src/modules/stats/objects/objects.stats.controller.ts
  server/src/modules/stats/objects/objects.stats.module.ts
  server/src/modules/stats/objects/objects.stats.service.ts
  server/src/modules/stats/slides/slides.stats.controller.ts
  server/src/modules/stats/slides/slides.stats.module.ts
  server/src/modules/stats/slides/slides.stats.service.ts
  server/src/modules/stats/stats.module.ts
  server/src/modules/stats/users/users.stats.controller.ts
  server/src/modules/stats/users/users.stats.module.ts
  server/src/modules/stats/users/users.stats.service.ts
Labels: backend, feature

#98 fix(ws)[OK-172] Correct ws auth and response object service
  server/src/gateway/gateway.ts
  server/src/gateway/providers/object.action.service.ts
  server/src/modules/auth/strategies/ws.strategy.ts
  server/src/modules/boards/boards.service.ts
  server/src/modules/response/response.service.ts
Labels: fix, backend

#99 feat(ws)[OK-175] Add ws handler for slides
  server/src/gateway/gateway.dto.ts
  server/src/gateway/gateway.module.ts
  server/src/gateway/gateway.ts
  server/src/gateway/providers/join.board.service.ts
  server/src/gateway/providers/join.slide.service.ts
  server/src/gateway/providers/slide.action.service.ts
  server/src/modules/auth/guards/board.permission.guard.ts
  server/src/shared/interfaces/auth/GwSocket.ts
Labels: backend, feature

#100 feat(ws)[OK-178] Add ws handler for objects
  server/src/enums/object.action.ts
  server/src/gateway/gateway.dto.ts
  server/src/gateway/gateway.module.ts
  server/src/gateway/gateway.ts
  server/src/gateway/providers/join.slide.service.ts
  server/src/gateway/providers/object.action.service.ts
  server/src/modules/auth/guards/board.permission.guard.ts
Labels: backend, feature

#101 fix(ws)[OK-180] Improve joining board ws handler
  server/src/gateway/providers/connection.service.ts
  server/src/gateway/providers/join.board.service.ts
  server/src/gateway/providers/object.action.service.ts
  server/src/modules/auth/guards/board.permission.guard.ts
  server/src/modules/auth/guards/ws.auth.guard.ts
  server/src/modules/boards/boards.service.ts
  server/src/shared/interfaces/BoardPermissionsInfo.ts
  server/src/shared/interfaces/auth/GwSocket.ts
Labels: fix, backend

#103 fix(ws)[OK-182] Owner join board fix
  server/src/modules/boards/boards.service.ts
Labels: fix, backend

#95 feat(Boards)[OK-159] Implement user board tables and ui loading for board tables
  client/package-lock.json
  client/package.json
  client/src/app/globals.css
  client/src/app/user-boards/page.tsx
  client/src/components/ExtendedPagination.tsx
  client/src/components/board/SlideControls/SlidePagination.tsx
  client/src/components/loading/BoardTableSkeleton.tsx
  client/src/components/loading/LoadingSpinner.tsx
  client/src/components/ui/badge.tsx
  client/src/components/ui/skeleton.tsx
  client/src/components/user-boards/BoardTable.tsx
  client/src/components/user-boards/BoardsPagination.tsx
  client/src/components/user-boards/CreateBoardButton.tsx
  client/src/components/user-boards/Header.tsx
  client/src/components/user-boards/PaginationDemo.tsx
  client/src/components/user-boards/Sidebar.tsx
  client/src/components/user-boards/TabButtons.tsx
  client/src/components/user-boards/UserBoardsActionButtons.tsx
  client/src/components/user-boards/board-table/BoardTable.tsx
  client/src/components/user-boards/board-table/CellContent.tsx
  client/src/enums/BoardPermission.ts
  client/src/enums/BoardTableColumns.ts
  client/src/enums/BoardsActiveTab.ts
  client/src/interfaces/responses/user-boards/board-response.ts
  client/src/interfaces/responses/user-boards/paginated-boards-response.ts
  client/src/lib/userBoardsUtils.ts
  client/src/mock-data/BoardsFetcher.ts
  client/tailwind.config.ts
Labels: frontend, feature

#104 chore(models)[OK-183] Remove unused models
  server/src/modules/objects/objects.module.ts
  server/src/modules/slides/slides.module.ts
  server/src/modules/slides/slides.service.ts
Labels: backend

#105 feat(Frontend)[OK-186] Introduce logger
  client/Dockerfile
  client/next.config.mjs
  client/src/app/actions/slideActions.ts
  client/src/classes/logger/ConsoleLogger.ts
  client/src/contexts/AuthContext.tsx
  client/src/enums/LogLevel.ts
  client/src/interfaces/LoggerOptions.ts
  client/src/lib/board/menuDataUtils.ts
  client/src/lib/logger.ts
  docker-compose.yml
Labels: technical, frontend, docker, feature

#107 feat(BoardDetails)[OK-187] Create proper userboards subdirectories structure to implement board details
  client/src/app/user-boards/[boardId]/layout.tsx
  client/src/app/user-boards/[boardId]/page.tsx
  client/src/app/user-boards/[boardId]/permissions/page.tsx
  client/src/app/user-boards/[boardId]/statistics/page.tsx
  client/src/app/user-boards/layout.tsx
  client/src/app/user-boards/page.tsx
  client/src/components/board-details/BoardDetails.tsx
  client/src/components/board-details/BoardDetailsSidebar.tsx
  client/src/components/board-details/BoardPermissions.tsx
  client/src/components/board-details/BoardStatistics.tsx
  client/src/contexts/CreateBoardContext.tsx
Labels: frontend

#108 feat(ws)[OK-181] Add ws error filter
  server/src/gateway/gateway.ts
  server/src/gateway/providers/connection.service.ts
  server/src/gateway/providers/join.slide.service.ts
  server/src/modules/boards/boards.service.ts
  server/src/shared/filters/http.error.filter.ts
  server/src/shared/filters/ws.error.filter.ts
  server/src/shared/interfaces/errors/ErrorResponse.ts
  server/src/shared/interfaces/errors/ValidationError.ts
Labels: backend, feature

#109 feat(BoardSidebar)[OK-188] Create BoardSidebar for board details
  client/src/app/user-boards/[boardId]/layout.tsx
  client/src/components/board-details/BoardDetailsSidebar.tsx
  client/src/components/board-details/BoardSidebar.tsx
  client/src/components/board-details/SidebarButton.tsx
Labels: frontend, feature

#110 feat(BoardPermissions)[OK-179] Create BoardPermissions view and reusable components from BoardTable
  client/package-lock.json
  client/package.json
  client/src/app/user-boards/[boardId]/permissions/page.tsx
  client/src/components/board-details/BoardPermissions.tsx
  client/src/components/board-details/BoardPermissions/BoardPermissions.tsx
  client/src/components/board-details/BoardPermissions/BoardPermissionsInfoDialog.tsx
  client/src/components/board-details/BoardPermissions/BoardPermissionsSelect.tsx
  client/src/components/ui/select.tsx
  client/src/components/user-boards/BoardHeader.tsx
  client/src/components/user-boards/board-table/BoardTable.tsx
  client/src/components/user-boards/board-table/BoardTableLeadRow.tsx
  client/src/interfaces/board-permissions-user.ts
Labels: frontend, feature

#112 feat(Modals)[OK-201] Create hovercards and modals for deletion buttons
  client/src/components/board-details/BoardPermissions/BoardPermissions.tsx
  client/src/components/board-details/BoardPermissions/DeleteCollaboratorButton.tsx
  client/src/components/user-boards/board-table/BoardDeletionButton.tsx
  client/src/components/user-boards/board-table/BoardDetailsButton.tsx
  client/src/components/user-boards/board-table/BoardTable.tsx
Labels: frontend, feature

#111 refactor[OK-173] Improve endpoint for returning boards with permissions
  server/src/enums/boards.ownership.filter.option.ts
  server/src/enums/boardsFilter.ts
  server/src/main.ts
  server/src/modules/boards/boards.controller.ts
  server/src/modules/boards/boards.dto.ts
  server/src/modules/boards/boards.service.ts
  server/src/modules/boards/filter.query.builder.ts
  server/src/modules/response/response.service.ts
  server/src/shared/interfaces/BoardWithoutSlides.ts
  server/src/shared/interfaces/response-objects/PaginatedUserBoards.ts
  server/src/shared/interfaces/response-objects/UserRelatedBoardResponseObject.ts
  server/src/shared/interfaces/response-objects/UserRelatedBoardsPaginatedResponseObject.ts
Labels: backend, refactor

#102 feat(boards)[OK-173] Add endpoint for fetching user-related boards
  server/src/app.module.ts
  server/src/enums/boardsFilter.ts
  server/src/main.ts
  server/src/modules/boards/boards.controller.ts
  server/src/modules/boards/boards.dto.ts
  server/src/modules/boards/boards.service.ts
  server/src/modules/boards/filter.query.builder.ts
  server/src/modules/stats/stats.module.ts
  server/src/shared/interfaces/BoardWithoutSlides.ts
  server/src/shared/interfaces/response-objects/PaginatedUserBoards.ts
Labels: backend, feature

#113 feat(ws)[OK-206] Return board info after joining
  server/src/gateway/gateway.module.ts
  server/src/gateway/gateway.ts
  server/src/gateway/providers/join.board.service.ts
  server/src/gateway/providers/object.action.service.ts
  server/src/modules/boards/boards.service.ts
  server/src/modules/response/response.service.ts
  server/src/shared/interfaces/BoardPermissionsInfo.ts
  server/src/shared/interfaces/BoardWithSlidesCount.ts
  server/src/shared/interfaces/ClientBoardInfo.ts
  server/src/shared/interfaces/response-objects/BoardResponseObject.ts
Labels: backend, feature

#116 feat(boards)[OK-210] Return permissions for fetching filtered boards
  server/src/gateway/providers/join.board.service.ts
  server/src/modules/boards/boards.controller.ts
  server/src/modules/boards/boards.dto.ts
  server/src/modules/boards/boards.service.ts
  server/src/modules/response/response.service.ts
  server/src/shared/interfaces/BoardWithoutSlides.ts
  server/src/shared/interfaces/PopulatedBoard.ts
  server/src/shared/interfaces/UserPermission.ts
  server/src/shared/interfaces/response-objects/BoardResponseObject.ts
  server/src/shared/interfaces/response-objects/PaginatedUserBoards.ts
  server/src/shared/interfaces/response-objects/UserResponseObject.ts
Labels: fix, backend, feature

#117 fix(name)[OK-170] Unify name for objects
  server/src/gateway/gateway.dto.ts
  server/src/modules/objects/objects.dto.ts
  server/src/modules/users/test/users.service.test.ts
  server/src/schemas/object/base.object.schema.ts
  server/src/shared/interfaces/fabric-js/ObjectFilter.ts
  server/src/shared/interfaces/fabric-js/ObjectPath.ts
  server/src/shared/interfaces/fabric-js/ObjectShadow.ts
  server/src/shared/interfaces/fabric-js/ObjectTextStyles.ts
  server/src/shared/interfaces/fabric-js/SlideObjectFilter.ts
  server/src/shared/interfaces/fabric-js/SlideObjectPath.ts
  server/src/shared/interfaces/response-objects/ObjectResponseObject.ts
  server/src/shared/interfaces/response-objects/UserResponseObject.ts
Labels: fix

#119 chore(deps)[OK-211] Fix security issue
  server/.depcheckrc
  server/package-lock.json
  server/package.json
Labels: technical, backend, dependencies

#123 feat(size)[OK-223] Add board size in BYTES
  server/package-lock.json
  server/package.json
  server/src/modules/boards/boards.service.ts
  server/src/modules/response/response.service.ts
  server/src/shared/interfaces/BoardWithoutSlides.ts
  server/src/shared/interfaces/response-objects/PaginatedUserBoards.ts
Labels: backend, feature

#124 refactor(stats)[OK-220] Unify names
  server/src/modules/stats/object/object.stats.controller.ts
  server/src/modules/stats/object/object.stats.module.ts
  server/src/modules/stats/object/object.stats.service.ts
  server/src/modules/stats/objects/objects.stats.controller.ts
  server/src/modules/stats/objects/objects.stats.module.ts
  server/src/modules/stats/slide/slide.stats.controller.ts
  server/src/modules/stats/slide/slides.stats.module.ts
  server/src/modules/stats/slide/slides.stats.service.ts
  server/src/modules/stats/slides/slides.stats.controller.ts
  server/src/modules/stats/slides/slides.stats.module.ts
  server/src/modules/stats/stats.module.ts
  server/src/modules/stats/user/user.stats.controller.ts
  server/src/modules/stats/user/user.stats.module.ts
  server/src/modules/stats/user/user.stats.service.ts
  server/src/modules/stats/users/users.stats.controller.ts
  server/src/modules/stats/users/users.stats.module.ts
Labels: backend, refactor

#131 feat(HomePage)[OK-231] Automatic redirection to /user-boards from the root route
  client/src/app/page.tsx
Labels: frontend

#122 feat(UserBoard)[OK-200] Integrate endpoint for fetching user-boards with frontend
  client/package-lock.json
  client/package.json
  client/src/app/user-boards/page.tsx
  client/src/components/user-boards/UserBoards.tsx
  client/src/components/user-boards/board-table/BoardTable.tsx
  client/src/components/user-boards/board-table/CellContent.tsx
  client/src/enums/BoardTableColumns.ts
  client/src/enums/BoardsActiveTab.ts
  client/src/interfaces/responses/permissions-response.ts
  client/src/interfaces/responses/user-boards/board-response.ts
  client/src/interfaces/responses/user-boards/paginated-boards-response.ts
  client/src/interfaces/responses/user-response.ts
  client/src/lib/bytesConverter.ts
  client/src/lib/dateUtils.ts
  client/src/lib/userBoardsUtils.ts
  client/src/mock-data/BoardsFetcher.ts
  client/src/services/fetchBoards.ts
Labels: frontend, test-required, feature

#125 fix(board-stats)[OK-225] Fix invalid ref, invalid type and typo
  server/src/modules/stats/board/board.stats.service.ts
  server/src/schemas/stats/board.stats.schema.ts
Labels: fix, backend

#126 feat(slide-stats)[OK-189] Add schema and basic logic
  server/src/modules/stats/slide/slides.stats.module.ts
  server/src/modules/stats/slide/slides.stats.service.ts
  server/src/schemas/stats/slide.stats.schema.ts
Labels: backend, feature

#129 feat(object-stats)[OK-190] Add schema and basic logic
  server/src/modules/stats/object/object.stats.module.ts
  server/src/modules/stats/object/object.stats.service.ts
  server/src/schemas/stats/object.stats.schema.ts
Labels: backend, feature

#130 feat(board-stats)[OK-228] Update schema
  server/src/modules/stats/board/board.stats.service.ts
  server/src/schemas/stats/board.stats.schema.ts
Labels: backend, feature

#135 fix(ws)[OK-235] Add slide number in emit event
  server/src/gateway/providers/slide.action.service.ts
Labels: fix, backend

#133 feat(stats)[OK-230] Add options to stats schemas
  server/src/schemas/stats/board.stats.schema.ts
  server/src/schemas/stats/object.stats.schema.ts
  server/src/schemas/stats/slide.stats.schema.ts
Labels: backend, feature

#132 refactor(stats)[OK-229] Rename StatsUserTimestamp to UserActionTimeline
  server/src/schemas/stats/board.stats.schema.ts
  server/src/schemas/stats/slide.stats.schema.ts
  server/src/shared/interfaces/UserActionTimeline.ts
Labels: backend, refactor

#137 refactor(mongo)[OK-202] Extract mongo module
  server/src/app.module.ts
  server/src/mongo/mongo.module.ts
Labels: backend, refactor

#138 fix(ws)[OK-234] Improve joining/leaving target
  server/src/gateway/gateway.module.ts
  server/src/gateway/gateway.ts
  server/src/gateway/providers/common.service.ts
  server/src/gateway/providers/connection.service.ts
  server/src/gateway/providers/join.board.service.ts
  server/src/gateway/providers/join.slide.service.ts
Labels: fix, backend

#139 fix(db)[OK-247] Fix mongodb connection while using docker
  server/src/mongo/mongo.module.ts
Labels: fix, backend, docker

#141 feat(ws)[OK-250] Add validators for core ws dto
  server/src/gateway/dto/board.data.ts
  server/src/gateway/dto/object.data.ts
  server/src/gateway/dto/slide.data.ts
  server/src/gateway/gateway.dto.ts
  server/src/gateway/gateway.ts
  server/src/gateway/providers/connection.service.ts
  server/src/gateway/providers/join.board.service.ts
  server/src/gateway/providers/join.slide.service.ts
  server/src/gateway/providers/object.action.service.ts
  server/src/gateway/providers/slide.action.service.ts
  server/src/modules/objects/objects.controller.ts
  server/src/modules/objects/objects.dto.ts
  server/src/modules/objects/objects.service.ts
Labels: backend, feature

#92 feat(websockets)[OK-130] Frontend websocket implementation and integration with the backend
  client/Dockerfile
  client/next.config.mjs
  client/package-lock.json
  client/package.json
  client/src/app/actions/boardActions.ts
  client/src/app/actions/slideActions.ts
  client/src/app/api/auth/google/route.ts
  client/src/app/api/auth/login/route.ts
  client/src/app/api/auth/signup/route.ts
  client/src/app/globals.css
  client/src/app/user-boards/(board-management)/[boardId]/layout.tsx
  client/src/app/user-boards/(board-management)/[boardId]/page.tsx
  client/src/app/user-boards/(board-management)/[boardId]/permissions/page.tsx
  client/src/app/user-boards/(board-management)/[boardId]/statistics/page.tsx
  client/src/app/user-boards/(board-management)/layout.tsx
  client/src/app/user-boards/(board-management)/page.tsx
  client/src/app/user-boards/(realtime-canvas)/[boardId]/slides/[slideIndex]/layout.tsx
  client/src/app/user-boards/(realtime-canvas)/[boardId]/slides/[slideIndex]/page.tsx
  client/src/app/user-boards/(realtime-canvas)/[boardId]/slides/layout.tsx
  client/src/app/user-boards/[boardId]/slides/[slideIndex]/layout.tsx
  client/src/classes/undo-redo-commands/AddCommand.ts
  client/src/classes/undo-redo-commands/ComplexCommand.ts
  client/src/classes/undo-redo-commands/ModifyCommand.ts
  client/src/classes/undo-redo-commands/RemoveCommand.ts
  client/src/components/board/SlideControls/SlidePagination.tsx
  client/src/components/board/Toolbar/Controls/FontStyleControls.tsx
  client/src/components/board/Toolbar/Controls/ObjectSpecificControls.tsx
  client/src/components/loading/SocketLoading.tsx
  client/src/components/ui/select.tsx
  client/src/components/ui/skeleton.tsx
  client/src/contexts/CanvasContext.tsx
  client/src/contexts/CreateBoardContext.tsx
  client/src/contexts/FileContext.tsx
  client/src/contexts/SlideControlsContext.tsx
  client/src/contexts/SocketContext.tsx
  client/src/contexts/UndoRedoContext.tsx
  client/src/hooks/auth/useHandleAuth.ts
  client/src/hooks/board/useCanvasEventListeners.tsx
  client/src/hooks/board/useMenuActions.ts
  client/src/hooks/socket/useSocketListeners.tsx
  client/src/interfaces/canvas-context.ts
  client/src/interfaces/socket/SocketCallbacksData.ts
  client/src/interfaces/socket/SocketEmitsData.ts
  client/src/interfaces/undo-redo-context.ts
  client/src/lib/authApiUtils.ts
  client/src/lib/board/fileUtils.ts
  client/src/lib/board/menuDataUtils.ts
  client/src/lib/board/socketEmitUtils.ts
  client/src/providers/KeydownListenerWrapper.tsx
Labels: frontend, tested-ok, feature

#114 feat(BoardDetails)[OK-209] Implement board details main view
  client/package-lock.json
  client/package.json
  client/src/app/user-boards/(board-management)/[boardId]/page.tsx
  client/src/app/user-boards/(board-management)/[boardId]/permissions/page.tsx
  client/src/components/board-details/BoardDetails.tsx
  client/src/components/board-details/BoardSidebar.tsx
  client/src/components/board-details/board-information/BoardDetails.tsx
  client/src/components/board-details/board-information/BoardInfoInputItem.tsx
  client/src/components/board-details/board-information/BoardInfoItem.tsx
  client/src/components/board-details/board-information/BoardNameField.tsx
  client/src/components/board-details/board-information/CollaboratingUsers.tsx
  client/src/components/board-details/board-permissions/BoardPermissions.tsx
  client/src/components/board-details/board-permissions/BoardPermissionsInfoDialog.tsx
  client/src/components/board-details/board-permissions/BoardPermissionsSelect.tsx
  client/src/components/board-details/board-permissions/DeleteCollaboratorButton.tsx
  client/src/components/loading/BoardDetailsInfoSkeleton.tsx
  client/src/components/ui/progress.tsx
  client/src/components/user-boards/Header.tsx
  client/src/hooks/board-details/useBoardName.ts
  client/src/interfaces/responses/board-details-response.ts
  client/src/mock-data/BoardDetailsFetcher.ts
Labels: frontend, feature

#118 feat(MetaData)[OK-66] Application metadata
  client/public/favicon/dark-mode/apple-touch-icon.png
  client/public/favicon/dark-mode/favicon-48x48.png
  client/public/favicon/dark-mode/favicon.ico
  client/public/favicon/dark-mode/favicon.svg
  client/public/favicon/dark-mode/site.webmanifest
  client/public/favicon/dark-mode/web-app-manifest-192x192.png
  client/public/favicon/dark-mode/web-app-manifest-512x512.png
  client/public/favicon/light-mode/apple-touch-icon.png
  client/public/favicon/light-mode/favicon-48x48.png
  client/public/favicon/light-mode/favicon.ico
  client/public/favicon/light-mode/favicon.svg
  client/public/favicon/light-mode/site.webmanifest
  client/public/favicon/light-mode/web-app-manifest-192x192.png
  client/public/favicon/light-mode/web-app-manifest-512x512.png
  client/src/app/auth/login/layout.tsx
  client/src/app/auth/signup/layout.tsx
  client/src/app/favicon.ico
  client/src/app/layout.tsx
  client/src/app/user-boards/(board-management)/[boardId]/layout.tsx
  client/src/app/user-boards/(board-management)/layout.tsx
Labels: frontend, feature

#146 feat(object-stats)[OK-257] Update schema
  server/src/modules/stats/object/object.stats.service.ts
  server/src/mongo/mongo.module.ts
  server/src/mongo/schemas/stats/object.stats.schema.ts
Labels: backend, feature

#143 feat(board-stats)[OK-240] Update schema
  server/src/modules/stats/board/board.stats.service.ts
  server/src/mongo/schemas/stats/board.stats.schema.ts
Labels: backend, feature

#147 feat(boards)[OK-243] Add endpoint for board details
  server/src/config/sample.ts
  server/src/gateway/providers/join.board.service.ts
  server/src/modules/boards/boards.controller.ts
  server/src/modules/boards/boards.service.ts
  server/src/modules/response/response.service.ts
  server/src/shared/interfaces/BoardWithSlideCount.ts
  server/src/shared/interfaces/ClientBoardInfo.ts
  server/src/shared/interfaces/PopulatedBoard.ts
  server/src/shared/interfaces/response-objects/BoardResponseObject.ts
  server/src/shared/interfaces/response-objects/PaginatedUserBoards.ts
Labels: backend, feature

#148 feat(BoardDetails)[OK-185] Integrate board details view with backend
  client/src/app/user-boards/(board-management)/[boardId]/error.tsx
  client/src/app/user-boards/(board-management)/[boardId]/layout.tsx
  client/src/app/user-boards/(board-management)/[boardId]/loading.tsx
  client/src/app/user-boards/(board-management)/[boardId]/page.tsx
  client/src/app/user-boards/(board-management)/[boardId]/permissions/loading.tsx
  client/src/app/user-boards/(board-management)/[boardId]/permissions/page.tsx
  client/src/components/board-details/board-information/BoardDetails.tsx
  client/src/components/board-details/board-information/CollaboratingUsers.tsx
  client/src/components/board-details/board-permissions/BoardPermissions.tsx
  client/src/components/loading/PermissionsPageSkeleton.tsx
  client/src/interfaces/board-permissions-user.ts
  client/src/interfaces/responses/board-details-response.ts
  client/src/mock-data/BoardDetailsFetcher.ts
  client/src/services/fetchBoardDetails.ts
  server/src/modules/boards/boards.controller.ts
Labels: frontend, test-required, feature

#149 feat(stats)[OK-254] Add actions enums, add last action to user stats schema
  server/src/modules/stats/object/object.stats.service.ts
  server/src/modules/stats/slide/slides.stats.service.ts
  server/src/modules/stats/user/user.stats.service.ts
  server/src/mongo/schemas/stats/object.stats.schema.ts
  server/src/mongo/schemas/stats/slide.stats.schema.ts
  server/src/mongo/schemas/stats/user.stats.schema.ts
  server/src/shared/enums/actions/board.action.ts
  server/src/shared/enums/actions/global.action.ts
  server/src/shared/enums/actions/object.action.ts
  server/src/shared/enums/actions/slide.action.ts
  server/src/shared/enums/actions/user.action.ts
Labels: backend, feature

#151 fix(slides)[OK-258] Rename slideCount
  client/src/contexts/SlideControlsContext.tsx
  client/src/contexts/SocketContext.tsx
  client/src/interfaces/socket/SocketCallbacksData.ts
Labels: fix

#150 feat(BoardDeletion)[OK-184] Implement board deletion
  client/src/app/actions/boardActions.ts
  client/src/components/user-boards/board-table/BoardDeletionButton.tsx
  client/src/components/user-boards/board-table/BoardTable.tsx
Labels: frontend, feature

#153 feat(guard)[OK-259] Add board access guard for http
  server/src/gateway/gateway.ts
  server/src/modules/auth/guards/board.access.guard.ts
  server/src/modules/auth/guards/board.permission.guard.ts
  server/src/modules/boards/boards.controller.ts
  server/src/modules/boards/boards.service.ts
Labels: backend

#154 feat(config)[OK-261] Add config file with default envs
  server/src/config/dev.config.ts
  server/src/config/sample.ts
  server/src/main.ts
  server/src/modules/auth/auth.module.ts
  server/src/modules/auth/strategies/google.strategy.ts
  server/src/modules/auth/strategies/jwt.strategy.ts
  server/src/modules/boards/boards.service.ts
  server/src/mongo/mongo.module.ts
Labels: backend, feature

#152 feat(Cursor)[OK-171] Add Cursor tracking on slide
  client/package-lock.json
  client/package.json
  client/src/components/board/Canvas.tsx
  client/src/components/board/Cursors/Cursors.tsx
  client/src/components/board/Cursors/cursors.module.css
  client/src/contexts/CanvasContext.tsx
  client/src/contexts/SocketContext.tsx
  client/src/interfaces/responses/cursor/cursor-position-emit.ts
  server/src/gateway/dto/cursor.data.ts
  server/src/gateway/gateway.module.ts
  server/src/gateway/gateway.ts
  server/src/gateway/providers/cursor.action.service.ts
Labels: frontend, backend, test-required, feature

#156 feat(permissions)[OK-238] Add granting permissions implementation
  server/src/modules/auth/auth.service.ts
  server/src/modules/auth/guards/board.access.guard.ts
  server/src/modules/boards/boards.controller.ts
  server/src/modules/boards/boards.dto.ts
  server/src/modules/boards/boards.module.ts
  server/src/modules/boards/boards.service.ts
  server/src/shared/interfaces/response-objects/CreatePermissionsStr.ts
  server/src/shared/interfaces/response-objects/GrantPermission.ts
Labels: backend, feature

#160 refactor(guard)[OK-270] Extract role guard from jwt guard
  server/src/modules/auth/auth.controller.ts
  server/src/modules/auth/guards/jwt.auth.guard.ts
  server/src/modules/auth/guards/role.auth.guard.ts
Labels: backend, feature

#158 feat(BoardPermissions)[OK-267] Granting permission to a given user
  client/Dockerfile
  client/next.config.mjs
  client/package-lock.json
  client/src/app/Providers.tsx
  client/src/app/actions/permissionsActions.ts
  client/src/app/layout.tsx
  client/src/app/user-boards/(board-management)/[boardId]/error.tsx
  client/src/app/user-boards/(board-management)/layout.tsx
  client/src/app/user-boards/(board-management)/permission-verify/loading.tsx
  client/src/app/user-boards/(board-management)/permission-verify/page.tsx
  client/src/app/user-boards/(realtime-canvas)/[boardId]/slides/[slideIndex]/page.tsx
  client/src/components/board-details/board-permissions/BoardPermissions.tsx
  client/src/components/board-details/board-permissions/BoardPermissionsSelect.tsx
  client/src/components/board-details/board-permissions/ShareBoardDialog.tsx
  client/src/components/board-permission-verify/PermissionVerifyFailure.tsx
  client/src/components/board-permission-verify/PermissionVerifySuccess.tsx
  client/src/components/board-permission-verify/PermissionVerifying.tsx
  client/src/components/board/HorizontalMenu.tsx
  client/src/components/main-header/AppLogo.tsx
  client/src/components/main-header/Header.tsx
  client/src/components/main-header/LougoutButton.tsx
  client/src/components/main-header/ThemeToggle.tsx
  client/src/components/main-header/UserInfo.tsx
  client/src/components/user-boards/AuthHeaderButtons.tsx
  client/src/components/user-boards/board-table/BoardTable.tsx
  client/src/components/user-boards/board-table/CellContent.tsx
  client/src/components/user-boards/main-header/UserInfo.tsx
  client/src/contexts/AuthContext.tsx
  client/src/contexts/SocketContext.tsx
  client/src/enums/BoardPermissionNum.ts
  client/src/interfaces/auth-context.ts
  client/src/interfaces/error-page/error-page.ts
  client/src/interfaces/responses/board-permission/generate-permission-code-response.ts
  client/src/interfaces/responses/board-permission/grant-permission-response.ts
  client/src/interfaces/responses/user-boards/board-response.ts
  client/src/interfaces/time-unit.ts
  client/src/lib/authApiUtils.ts
  client/src/lib/boardPermissionConverter.ts
  client/src/lib/dateUtils.ts
  client/src/lib/stringConverter.ts
Labels: fix, frontend, test-required, feature

#161 docs(readme)[OK-273] Add video link to the README
  README.md
Labels: documentation

#162 fix(request)[OK-274] Introduce requestService and socketService
  client/src/app/actions/boardActions.ts
  client/src/app/actions/permissionsActions.ts
  client/src/app/api/auth/google/route.ts
  client/src/app/api/auth/login/route.ts
  client/src/app/api/auth/signup/route.ts
  client/src/app/user-boards/(board-management)/[boardId]/layout.tsx
  client/src/app/user-boards/(board-management)/[boardId]/page.tsx
  client/src/app/user-boards/(board-management)/[boardId]/permissions/page.tsx
  client/src/components/user-boards/board-table/BoardTable.tsx
  client/src/contexts/SocketContext.tsx
  client/src/services/board/fetchBoardDetails.ts
  client/src/services/board/fetchBoards.ts
  client/src/services/requestService.ts
  client/src/services/socketService.ts
Labels: frontend, refactor

#163 refactor(auth)[OK-275] Refactor API Routes to Actions
  client/src/app/actions/authActions.ts
  client/src/app/api/auth/google/route.ts
  client/src/app/api/auth/login/route.ts
  client/src/app/api/auth/logout/route.ts
  client/src/app/api/auth/signup/route.ts
  client/src/contexts/AuthContext.tsx
  client/src/hooks/auth/useHandleAuth.ts
  client/src/services/requestService.ts
Labels: frontend, tested-ok, refactor

#164 refactor(fetcher)[OK-276] Add boards fetcher to server component
  client/package-lock.json
  client/package.json
  client/src/app/user-boards/(board-management)/loading.tsx
  client/src/app/user-boards/(board-management)/page.tsx
  client/src/components/loading/UserBoardsSkeleton.tsx
  client/src/components/user-boards/UserBoards.tsx
  client/src/components/user-boards/board-table/BoardDeletionButton.tsx
  client/src/components/user-boards/board-table/BoardTable.tsx
  client/src/enums/BoardsActiveTab.ts
Labels: frontend, tested-ok, refactor

#157 fix(docker)[OK-249] Fix docker and envs
  .github/workflows/docker.yml
  client/Dockerfile
  client/next.config.mjs
  client/src/services/socketService.ts
  docker-compose.yml
  server/Dockerfile
Labels: fix, technical, frontend, backend, docker

#167 fix(frontend)[OK-279] Remove header in next config and use uuid and add useRouter to authContext and rename env
  client/next.config.mjs
  client/package-lock.json
  client/package.json
  client/src/contexts/AuthContext.tsx
  client/src/hooks/auth/useGoogleAuth.ts
  client/src/lib/authApiUtils.ts
Labels: fix, frontend

#168 feat(ShareBoardDialog)[OK-280] Show whole link in ShareBoardDialog
  client/src/components/board-details/board-permissions/ShareBoardDialog.tsx
Labels: frontend

#170 refactor(stats-schemas)[OK-282] Change Types.ObjectId to string
  server/src/mongo/schemas/stats/board.stats.schema.ts
  server/src/mongo/schemas/stats/object.stats.schema.ts
  server/src/mongo/schemas/stats/slide.stats.schema.ts
  server/src/mongo/schemas/stats/user.stats.schema.ts
Labels: backend, refactor

#155 feat(object-stats)[OK-198] Integrate saving
  server/src/gateway/gateway.module.ts
  server/src/gateway/providers/object.action.service.ts
  server/src/modules/stats/object/object.stats.module.ts
  server/src/modules/stats/object/object.stats.service.ts
  server/src/modules/stats/stats.module.ts
Labels: backend, feature

#173 feat(google)[OK-286] Disable google auth on production
  client/next.config.mjs
  client/src/app/actions/authActions.ts
  client/src/app/auth/login/LoginCard.tsx
  client/src/app/auth/signup/SignupCard.tsx
Labels: frontend
