Repository OBELISK-TEAM/OBELISK, pull requests merged in 2024-11, with the labels that each got.

#175 chore(docker)[OK-295] Persist db data when using docker, update docs, add missing envs
  .github/workflows/docker.yml
  docker-compose.yml
  docs/API.md
  docs/CONTRIBUTING.md
  docs/INSTALL.md
Labels: technical, docker

#174 chore(users)[OK-285] Change password and mail requirements
  server/src/gateway/dto/cursor.data.ts
  server/src/gateway/gateway.ts
  server/src/gateway/providers/cursor.action.service.ts
  server/src/modules/users/users.dto.ts
Labels: backend

#179 fix(Cursors)[OK-302] Fix bug with cursors position while zoom
  client/src/components/board/cursors/Cursor.tsx
  client/src/components/board/cursors/Cursors.tsx
Labels: fix, frontend, tested-ok

#172 feat(object-stats)[OK-296] Handle delete
  server/src/gateway/providers/object.action.service.ts
  server/src/gateway/providers/slide.action.service.ts
  server/src/modules/boards/boards.module.ts
  server/src/modules/boards/boards.service.ts
  server/src/modules/stats/object/object.stats.service.ts
Labels: backend, feature

#177 feat(canvas)[OK-138] Add debouncing technique for actions on board
  client/src/components/board/cursors/Cursors.tsx
  client/src/components/board/toolbar-controls/FontStyleControls.tsx
  client/src/components/board/toolbar-controls/ObjectSpecificControls.tsx
  client/src/components/board/toolbar/Toolbar.tsx
  client/src/config/delayConfig.ts
  client/src/contexts/CanvasContext.tsx
  client/src/contexts/MenuDataContext.tsx
  client/src/contexts/ToolbarContext.tsx
  client/src/contexts/UndoRedoContext.tsx
  client/src/hooks/board/useCanvasEventListeners.tsx
  client/src/hooks/board/useMenuActions.ts
  client/src/interfaces/canvas-context.ts
  client/src/lib/board/canvasUtils.ts
  client/src/types/HandleToolbarChangeDebounced.ts
Labels: frontend, test-required, feature

#176 feat(rabbit)[OK-284] Add RabbitMQ microservice for handling mailing system with proxy client
  .github/workflows/docker.yml
  docker-compose.yml
  server/.depcheckrc
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/config/cors.config.ts
  server/src/config/dev.config.ts
  server/src/config/logger.config.ts
  server/src/config/mailing.config.ts
  server/src/config/mongo.config.ts
  server/src/config/pipe.config.ts
  server/src/config/rabbit.config.ts
  server/src/gateway/gateway.ts
  server/src/mailing/consumer/consumer.controller.ts
  server/src/mailing/consumer/consumer.module.ts
  server/src/mailing/consumer/consumer.service.ts
  server/src/mailing/consumer/templates/welcome.hbs
  server/src/mailing/mailing.module.ts
  server/src/mailing/producer/producer.controller.ts
  server/src/mailing/producer/producer.module.ts
  server/src/mailing/producer/producer.service.ts
  server/src/main.ts
  server/src/modules/auth/auth.controller.ts
  server/src/modules/auth/auth.module.ts
  server/src/modules/auth/auth.service.ts
  server/src/modules/auth/guards/board.access.guard.ts
  server/src/modules/auth/guards/role.auth.guard.ts
  server/src/modules/boards/boards.controller.ts
  server/src/modules/users/test/users.controller.test.ts
  server/src/mongo/mongo.module.ts
  server/src/shared/decorators/message.decorator.ts
  server/src/shared/decorators/permissions.decorator.ts
  server/src/shared/decorators/roles.decorator.ts
  server/src/shared/decorators/users.decorator.ts
  server/src/shared/decorators/ws.client.decorator.ts
  server/src/shared/interfaces/mailing/Message.ts
  server/test/app.e2e-spec.ts
  server/tsconfig.json
Labels: backend, docker, feature, refactor

#171 feat(envs)[OK-289] Add slide limit per board
  .github/workflows/docker.yml
  docker-compose.yml
  docs/INSTALL.md
  server/nest-cli.json
  server/src/config/dev.config.ts
  server/src/mailing/consumer/consumer.service.ts
  server/src/mailing/templates/welcome.hbs
  server/src/modules/boards/boards.service.ts
  server/src/modules/slides/slides.service.ts
Labels: fix, backend, feature

#182 fix(gateway)[OK-306] Add GatewayModule in app module
  server/src/app.module.ts
Labels: fix, backend

#184 ci(health)[OK-308] Add server health check to docker CI pipeline
  .github/workflows/docker.yml
  server/src/app.module.ts
  server/src/modules/health/health.controller.ts
  server/src/modules/health/health.module.ts
Labels: backend, CI, docker

#181 feat(slide-stats)[OK-197] Integrate saving
  server/src/gateway/gateway.module.ts
  server/src/gateway/providers/common.service.ts
  server/src/gateway/providers/join.slide.service.ts
  server/src/gateway/providers/object.action.service.ts
  server/src/gateway/providers/slide.action.service.ts
  server/src/modules/boards/boards.module.ts
  server/src/modules/boards/boards.service.ts
  server/src/modules/stats/slide/slides.stats.module.ts
  server/src/modules/stats/slide/slides.stats.service.ts
  server/src/mongo/schemas/stats/slide.stats.schema.ts
  server/src/shared/enums/actions/slide.action.ts
Labels: backend, feature

#180 feat(share board)[OK-291] Add share button in board view
  client/src/components/board/HorizontalMenu.tsx
  client/src/contexts/MenuDataContext.tsx
  client/src/enums/MenuActions.ts
  client/src/hooks/board/useMenuActions.ts
  client/src/interfaces/menu-data-context.ts
Labels: frontend

#186 refactor(button styles)[OK-272] Adjust user boards row buttons
  client/src/components/user-boards/board-table/BoardDeletionButton.tsx
  client/src/components/user-boards/board-table/BoardDetailsButton.tsx
  client/src/components/user-boards/board-table/BoardTable.tsx
Labels: frontend

#188 feat(health-path)[OK-313] Create health api call
  client/src/app/api/health/route.ts
Labels: frontend, CI

#189 ci(health)[OK-309] Add client health check to docker CI pipeline
  .github/workflows/docker.yml
Labels: frontend, CI, docker

#190 feat(env)[OK-290] Integrate slide limit and board max size with frontend
  client/Dockerfile
  client/next.config.mjs
  client/src/components/board-details/board-information/BoardDetails.tsx
  client/src/config/boardConfig.ts
  client/src/contexts/SlideControlsContext.tsx
  docker-compose.yml
Labels: frontend

#191 ci(health)[OK-310] Add MongoDB health check to docker CI pipeline
  .github/workflows/docker.yml
Labels: backend, CI, docker

#187 feat(redirect)[OK-292] Redirect to subpage from saved path
  client/package-lock.json
  client/package.json
  client/src/contexts/AuthContext.tsx
  client/src/lib/urlUtils.ts
  client/src/middleware.ts
Labels: frontend

#192 ci(health)[OK-311] Add RabbitMQ health check to docker CI pipeline
  .github/workflows/docker.yml
Labels: backend, CI

#194 feat(boards)[OK-317] Add endpoint for changing board name
  server/src/modules/boards/boards.controller.ts
  server/src/modules/boards/boards.dto.ts
  server/src/modules/boards/boards.service.ts
Labels: backend, feature

#185 feat(Permissions)[OK-271] Create viewer view of the board
  client/src/app/actions/permissionsActions.ts
  client/src/app/user-boards/(board-management)/[boardId]/error.tsx
  client/src/app/user-boards/(board-management)/[boardId]/layout.tsx
  client/src/app/user-boards/(board-management)/[boardId]/page.tsx
  client/src/app/user-boards/(board-management)/page.tsx
  client/src/app/user-boards/(realtime-canvas)/[boardId]/slides/[slideIndex]/page.tsx
  client/src/components/board-details/BoardSidebar.tsx
  client/src/components/board-details/board-information/BoardDetails.tsx
  client/src/components/board-details/board-permissions/BoardPermissions.tsx
  client/src/components/board-details/board-permissions/BoardPermissionsSelect.tsx
  client/src/components/board-details/board-permissions/ShareBoardDialog.tsx
  client/src/components/board-details/sidebar/BoardSidebar.tsx
  client/src/components/board-details/sidebar/SidebarContent.tsx
  client/src/components/board-details/sidebar/SidebarContentClient.tsx
  client/src/components/board/HorizontalMenu.tsx
  client/src/components/board/slide-controls/SlideControls.tsx
  client/src/components/error/BoardDetailsError.tsx
  client/src/components/error/UserBoardsError.tsx
  client/src/components/loading/LoadingSidebar.tsx
  client/src/components/user-boards/board-table/BoardTable.tsx
  client/src/contexts/CanvasContext.tsx
  client/src/contexts/SocketContext.tsx
  client/src/hooks/window/useScrollToTop.ts
  client/src/interfaces/error-page/error-page.ts
  client/src/interfaces/sidebar-nav-items.ts
  client/src/interfaces/user-capabilities.ts
  client/src/lib/board/canvasUtils.ts
  client/src/lib/board/horizontalMenuUtils.ts
  client/src/lib/boardPermissionConverter.ts
  client/src/lib/permissionUtils.ts
  client/src/types/permissions/CapabilityFunctions.ts
  client/src/types/permissions/CapabilityPermissionMap.ts
Labels: frontend, test-required, feature

#193 chore(core)[OK-316] Introduce core module
  server/src/app.module.ts
  server/src/gateway/dto/object.data.ts
  server/src/gateway/gateway.module.ts
  server/src/gateway/providers/join.board.service.ts
  server/src/gateway/providers/join.slide.service.ts
  server/src/gateway/providers/object.action.service.ts
  server/src/gateway/providers/slide.action.service.ts
  server/src/modules/auth/auth.module.ts
  server/src/modules/auth/guards/board.access.guard.ts
  server/src/modules/core/boards/boards.controller.ts
  server/src/modules/core/boards/boards.dto.ts
  server/src/modules/core/boards/boards.module.ts
  server/src/modules/core/boards/boards.service.ts
  server/src/modules/core/boards/filter.query.builder.ts
  server/src/modules/core/core.module.ts
  server/src/modules/core/objects/objects.controller.ts
  server/src/modules/core/objects/objects.dto.ts
  server/src/modules/core/objects/objects.module.ts
  server/src/modules/core/objects/objects.service.ts
  server/src/modules/core/slides/slides.controller.ts
  server/src/modules/core/slides/slides.dto.ts
  server/src/modules/core/slides/slides.module.ts
  server/src/modules/core/slides/slides.service.ts
Labels: backend

#196 feat(permission)[OK-318] Add permission endpoint for modifying
  server/src/modules/core/boards/boards.controller.ts
  server/src/modules/core/boards/boards.dto.ts
  server/src/modules/core/boards/boards.service.ts
Labels: backend, feature

#195 feat(board-name)[OK-212] Implement action of updating the board name
  client/src/app/actions/boardActions.ts
  client/src/components/board-details/board-information/BoardDetails.tsx
  client/src/components/board-details/board-information/BoardInfoInputItem.tsx
  client/src/components/board-details/board-information/BoardNameField.tsx
  client/src/hooks/board-details/useBoardName.ts
  client/src/hooks/board-details/useBoardNameField.ts
Labels: frontend, test-required, feature

#198 feat(modify-permission)[OK-319] Integrate action of updating and deleting permissions with frontend
  client/src/app/actions/permissionsActions.ts
  client/src/components/board-details/board-permissions/BoardPermissions.tsx
  client/src/components/board-details/board-permissions/BoardPermissionsSelect.tsx
  client/src/components/board-details/board-permissions/DeleteCollaboratorButton.tsx
  client/src/components/board-details/board-permissions/ShareBoardDialog.tsx
  client/src/interfaces/board-permissions-user.ts
  client/src/interfaces/requests/board-permission-modify-request.ts
Labels: frontend, tested-ok, feature

#199 feat(start-page)[OK-39] Implement start page
  client/public/images/start-page/fallback-image.jpg
  client/public/images/start-page/medium-teams.jpg
  client/public/images/start-page/real-time-collaboration.jpg
  client/public/images/start-page/small-teams.jpg
  client/src/app/page.tsx
  client/src/components/main-header/Header.tsx
  client/src/components/start/animated-section/StartPageAnimatedSection.tsx
  client/src/components/start/card-section/StartPageCardItem.tsx
  client/src/components/start/card-section/StartPageCardSection.tsx
  client/src/components/start/hexagons-section/StartPageHexagon.tsx
  client/src/components/start/hexagons-section/StartPageHexagonsSection.tsx
  client/src/components/start/text-section/TextSection.tsx
  client/src/components/user-boards/AuthHeaderButtons.tsx
  client/src/data/start/get-started-data.tsx
  client/src/data/start/hexagons-data.ts
  client/src/data/start/join-community-data.tsx
  client/src/data/start/target-audience-data.ts
  client/src/data/start/tool-features-data.ts
  client/src/data/start/useful-capabilities-section.ts
  client/src/interfaces/start-page/card-section.ts
  client/src/interfaces/start-page/card.ts
  client/src/interfaces/start-page/hexagons-section.ts
  client/src/interfaces/start-page/text-section.ts
  client/src/middleware.ts
  client/tailwind.config.ts
Labels: frontend, feature

#197 feat(board-stats)[OK-196] Integrate saving
  server/src/gateway/gateway.module.ts
  server/src/gateway/providers/common.service.ts
  server/src/gateway/providers/join.board.service.ts
  server/src/gateway/providers/object.action.service.ts
  server/src/gateway/providers/slide.action.service.ts
  server/src/modules/core/boards/boards.module.ts
  server/src/modules/core/boards/boards.service.ts
  server/src/modules/stats/board/board.stats.module.ts
  server/src/modules/stats/board/board.stats.service.ts
  server/src/modules/stats/slide/slides.stats.service.ts
  server/src/mongo/schemas/stats/board.stats.schema.ts
  server/src/shared/enums/actions/board.action.ts
  server/src/shared/enums/actions/slide.action.ts
  server/src/shared/interfaces/UserActionTimeline.ts
Labels: backend, feature

#201 feat(board-stats)[OK-192] Add getActiveUsersOverTime endpoint
  server/src/modules/stats/board/board.stats.controller.ts
  server/src/modules/stats/board/board.stats.service.ts
  server/src/shared/interfaces/stats/ChartData.ts
Labels: backend, feature

#202 feat(slide-stats)[OK-193] Add endpoint for fetching heatmap for slide actions
  server/src/modules/stats/slide/slide.stats.controller.ts
  server/src/modules/stats/slide/slides.stats.service.ts
  server/src/shared/interfaces/stats/HeatmapPoint.ts
Labels: backend, feature

#205 feat(canvasReducer)[OK-350] Make Drawing Mode the default option
  client/src/reducers/canvasReducer.ts
Labels: frontend

#203 feat(board-stats)[OK-340] Add getTotalUniqeVisitors endpoint
  server/src/modules/stats/board/board.stats.controller.ts
  server/src/modules/stats/board/board.stats.service.ts
Labels: backend, feature

#208 feat(BoardDetailsSidebar)[OK-358] Make the sidebar in board details view constantly unrolled
  client/src/app/user-boards/(board-management)/[boardId]/_components/board-details-sidebar/BoardDetailsSidebar.tsx
  client/src/app/user-boards/(board-management)/[boardId]/_components/board-details-sidebar/BoardDetailsSidebarContentClient.tsx
Labels: frontend

#210 feat(Icons)[OK-360] Hide or remove unnecessary buttons on the board view
  client/src/app/user-boards/(realtime-canvas)/[boardId]/slides/[slideIndex]/_components/board-sidebar/BoardSidebar.tsx
  client/src/app/user-boards/(realtime-canvas)/[boardId]/slides/[slideIndex]/page.tsx
  client/src/contexts/MenuDataContext.tsx
Labels: frontend

#211 feat[OK-357] Alter start page text content
  client/src/data/start-page/get-started-data.tsx
  client/src/data/start-page/hexagons-data.ts
  client/src/data/start-page/join-community-data.tsx
  client/src/data/start-page/target-audience-data.ts
  client/src/data/start-page/tool-features-data.ts
  client/src/data/start-page/useful-capabilities-section.ts
Labels: frontend

#207 feat(Stats)[OK-352] Implement board statistics page with initial statistics
  client/package-lock.json
  client/package.json
  client/src/app/globals.css
  client/src/app/user-boards/(board-management)/[boardId]/_components/board-details-sidebar/BoardDetailsSidebarContentClient.tsx
  client/src/app/user-boards/(board-management)/[boardId]/statistics/_components/BoardStatistics.tsx
  client/src/app/user-boards/(board-management)/[boardId]/statistics/_components/StatisticsTab.tsx
  client/src/app/user-boards/(board-management)/[boardId]/statistics/activity/_components/ActiveUsersCard.tsx
  client/src/app/user-boards/(board-management)/[boardId]/statistics/activity/page.tsx
  client/src/app/user-boards/(board-management)/[boardId]/statistics/layout.tsx
  client/src/app/user-boards/(board-management)/[boardId]/statistics/page.tsx
  client/src/app/user-boards/(board-management)/[boardId]/statistics/permissions-management/page.tsx
  client/src/app/user-boards/(board-management)/[boardId]/statistics/time-spent/_components/UniqueVisitors.tsx
  client/src/app/user-boards/(board-management)/[boardId]/statistics/time-spent/page.tsx
  client/src/app/user-boards/(board-management)/_components/UserBoards.tsx
  client/src/app/user-boards/(board-management)/_components/board-table/BoardTable.tsx
  client/src/app/user-boards/(board-management)/page.tsx
  client/src/components/common/date-picker/DateRangePicker.tsx
  client/src/components/common/date-picker/DateRangeSelector.tsx
  client/src/components/common/statistics/StatisticsCard.tsx
  client/src/components/common/statistics/StatisticsChart.tsx
  client/src/components/common/statistics/SummaryCard.tsx
  client/src/components/common/tab-buttons/TabButtons.tsx
  client/src/components/ui/calendar.tsx
  client/src/components/ui/chart.tsx
  client/src/components/ui/popover.tsx
  client/src/config/statsConfig.ts
  client/src/enums/BoardDetailsNavItemLabel.ts
  client/src/enums/TimeInterval.ts
  client/src/enums/active-tab/BoardsActiveTab.ts
  client/src/enums/active-tab/StatisticsActiveTab.ts
  client/src/hooks/stats/useDateRange.ts
  client/src/interfaces/date-range.ts
  client/src/interfaces/requests/active-users-request.ts
  client/src/interfaces/responses/statistics/active-users-response.ts
  client/src/interfaces/sidebar-nav-items.ts
  client/src/interfaces/stats/statistics-card.ts
  client/src/interfaces/stats/statistics-chart.ts
  client/src/interfaces/time-interval.ts
  client/src/lib/colorUtils.ts
  client/src/lib/dateUtils.ts
  client/src/lib/userBoardsUtils.ts
  client/src/services/statistics/fetchBoardActiveUsersStats.ts
  client/src/services/statistics/fetchUniqueVisitors.ts
Labels: frontend, test-required, feature
