Repository OBELISK-TEAM/OBELISK, pull requests merged in 2024-12, with the labels that each got.

#204 chore(dir)[OK-349] Move mongo, gw, mailing modules to module folder
  server/nest-cli.json
  server/src/app.module.ts
  server/src/modules/auth/auth.module.ts
  server/src/modules/auth/auth.service.ts
  server/src/modules/core/boards/boards.module.ts
  server/src/modules/core/boards/boards.service.ts
  server/src/modules/core/boards/filter.query.builder.ts
  server/src/modules/core/objects/objects.dto.ts
  server/src/modules/core/objects/objects.service.ts
  server/src/modules/core/slides/slides.service.ts
  server/src/modules/gateway/dto/board.data.ts
  server/src/modules/gateway/dto/cursor.data.ts
  server/src/modules/gateway/dto/object.data.ts
  server/src/modules/gateway/dto/slide.data.ts
  server/src/modules/gateway/gateway.module.ts
  server/src/modules/gateway/gateway.ts
  server/src/modules/gateway/providers/common.service.ts
  server/src/modules/gateway/providers/connection.service.ts
  server/src/modules/gateway/providers/cursor.action.service.ts
  server/src/modules/gateway/providers/join.board.service.ts
  server/src/modules/gateway/providers/join.slide.service.ts
  server/src/modules/gateway/providers/object.action.service.ts
  server/src/modules/gateway/providers/slide.action.service.ts
  server/src/modules/mailing/consumer/consumer.controller.ts
  server/src/modules/mailing/consumer/consumer.module.ts
  server/src/modules/mailing/consumer/consumer.service.ts
  server/src/modules/mailing/mailing.module.ts
  server/src/modules/mailing/producer/producer.controller.ts
  server/src/modules/mailing/producer/producer.module.ts
  server/src/modules/mailing/producer/producer.service.ts
  server/src/modules/mailing/templates/welcome.hbs
  server/src/modules/mongo/mongo.module.ts
  server/src/modules/mongo/schemas/board/base.board.schema.ts
  server/src/modules/mongo/schemas/board/super.board.schema.ts
  server/src/modules/mongo/schemas/object/base.object.schema.ts
  server/src/modules/mongo/schemas/object/super.object.schema.ts
  server/src/modules/mongo/schemas/slide/base.slide.schema.ts
  server/src/modules/mongo/schemas/slide/super.slide.schema.ts
  server/src/modules/mongo/schemas/stats/board.stats.schema.ts
  server/src/modules/mongo/schemas/stats/object.stats.schema.ts
  server/src/modules/mongo/schemas/stats/slide.stats.schema.ts
  server/src/modules/mongo/schemas/stats/user.stats.schema.ts
  server/src/modules/mongo/schemas/user.schema.ts
  server/src/modules/response/response.service.ts
  server/src/modules/stats/board/board.stats.module.ts
  server/src/modules/stats/board/board.stats.service.ts
  server/src/modules/stats/object/object.stats.module.ts
  server/src/modules/stats/object/object.stats.service.ts
  server/src/modules/stats/slide/slides.stats.module.ts
  server/src/modules/stats/slide/slides.stats.service.ts
  server/src/modules/stats/user/user.stats.module.ts
  server/src/modules/stats/user/user.stats.service.ts
  server/src/modules/users/test/users.service.test.ts
  server/src/modules/users/users.module.ts
  server/src/modules/users/users.service.ts
  server/src/shared/interfaces/BoardWithSlideCount.ts
  server/src/shared/interfaces/PopulatedBoard.ts
  server/src/shared/interfaces/auth/SafeUserDoc.ts
  server/src/shared/interfaces/response-objects/ObjectResponseObject.ts
Labels: backend

#206 feat(board-stats)[OK-339] Add getTimesSpentOnBoardInMs endpoint
  server/src/modules/core/boards/boards.module.ts
  server/src/modules/gateway/gateway.module.ts
  server/src/modules/stats/board/board.stats.controller.ts
  server/src/modules/stats/board/board.stats.module.ts
  server/src/modules/stats/board/board.stats.service.ts
  server/src/modules/stats/object/object.stats.module.ts
  server/src/modules/stats/slide/slides.stats.module.ts
  server/src/shared/interfaces/stats/NumericalTimelineChartData.ts
  server/src/shared/interfaces/stats/TimeSpentData.ts
Labels: backend, feature

#213 fix(DrawingMode)[OK-363] Change drawing mode to selection mode when user has editor permission
  client/src/contexts/CanvasContext.tsx
Labels: fix, frontend

#215 fix(stats)[OK-353] Enable nestJS shutdown hooks and fix setting leaveDate in stats
  server/src/main.ts
  server/src/modules/stats/board/board.stats.module.ts
  server/src/modules/stats/board/board.stats.service.ts
  server/src/modules/stats/slide/slides.stats.service.ts
Labels: fix, backend, priority

#218 fix(board)[OK-370] Add fixes for board
  client/src/app/user-boards/(board-management)/_components/board-table/CellContent.tsx
  client/src/app/user-boards/(realtime-canvas)/[boardId]/slides/[slideIndex]/_components/HorizontalMenu.tsx
  client/src/app/user-boards/(realtime-canvas)/[boardId]/slides/[slideIndex]/_components/board-sidebar/BoardSidebar.tsx
  client/src/app/user-boards/(realtime-canvas)/[boardId]/slides/[slideIndex]/_components/board-sidebar/BoardSidebarItem.tsx
  client/src/app/user-boards/(realtime-canvas)/[boardId]/slides/[slideIndex]/_components/toolbar/ToolbarInput.tsx
  client/src/app/user-boards/(realtime-canvas)/[boardId]/slides/[slideIndex]/_components/toolbar/controls/ObjectSpecificControls.tsx
  client/src/config/brushConfig.ts
  client/src/contexts/CanvasContext.tsx
  client/src/contexts/MenuDataContext.tsx
  client/src/enums/CanvasReducerAction.ts
  client/src/hooks/board/useMenuActions.ts
  client/src/interfaces/canvas-context.ts
  client/src/interfaces/menu-data-context.ts
  client/src/lib/board/canvasUtils.ts
  client/src/reducers/canvasReducer.ts
  client/src/types/CanvasActionHandler.ts
  client/src/types/CanvasReducer.ts
Labels: fix, frontend, test-required

#219 feat(TimeSpent)[OK-372] Integrate time spent stat endpoints with frontend
  client/src/app/user-boards/(board-management)/[boardId]/statistics/activity/_components/ActiveUsersCard.tsx
  client/src/app/user-boards/(board-management)/[boardId]/statistics/time-spent/_components/TimeSpentCard.tsx
  client/src/app/user-boards/(board-management)/[boardId]/statistics/time-spent/_components/UniqueVisitors.tsx
  client/src/app/user-boards/(board-management)/[boardId]/statistics/time-spent/page.tsx
  client/src/components/common/statistics/StatisticsCard.tsx
  client/src/components/common/statistics/StatisticsPieChart.tsx
  client/src/components/common/statistics/StatisticsTimelineChart.tsx
  client/src/components/common/statistics/SummaryCard.tsx
  client/src/interfaces/responses/statistics/time-spent-response.ts
  client/src/interfaces/stats/statistics-card.ts
  client/src/interfaces/stats/statistics-pie-chart.ts
  client/src/interfaces/stats/statistics-timeline-chart.ts
  client/src/lib/dateUtils.ts
  client/src/services/statistics/fetchTimeSpent.ts
Labels: frontend, test-required, feature

#220 fix(EndDateInterval)[OK-373] Include end date interval containing zero
  client/src/app/user-boards/(board-management)/[boardId]/statistics/activity/page.tsx
  client/src/lib/dateUtils.ts
Labels: fix, frontend

#224 fix(intervals)[OK-275] Make smaller intervals in timeline charts
  client/src/app/user-boards/(board-management)/[boardId]/statistics/_components/StatisticsTab.tsx
  client/src/app/user-boards/(board-management)/[boardId]/statistics/time-spent/_components/TimeSpentCard.tsx
  client/src/components/common/dialogs/ShareBoardDialog.tsx
  client/src/lib/dateUtils.ts
Labels: fix, frontend

#223 feat(board-stats)[OK-374] Add log to permissions stats
  server/src/modules/core/boards/boards.service.ts
  server/src/modules/mongo/schemas/stats/board.stats.schema.ts
  server/src/modules/stats/board/board.stats.service.ts
Labels: backend, feature
