Repository OBELISK-TEAM/OBELISK, pull requests merged in 2024-09, with the labels that each got.

#65 docs(auth)[OK-117] Complete Swagger docs
  backend/src/main.ts
  backend/src/modules/auth/auth.controller.ts
  backend/src/shared/interfaces/AuthToken.ts
Labels: documentation, backend

#67 feat(slides/slide-objects)[OK-116] Add response object methods
  backend/src/modules/boards/boards.service.ts
  backend/src/modules/slide-objects/slide-objects.controller.ts
  backend/src/modules/slide-objects/slide-objects.service.ts
  backend/src/modules/slides/slides.controller.ts
  backend/src/modules/slides/slides.service.ts
  backend/src/modules/users/users.service.ts
  backend/src/schemas/slide-object.schema.ts
  backend/src/schemas/slide.schema.ts
  backend/src/shared/interfaces/response-objects/BoardResponseObject.ts
  backend/src/shared/interfaces/response-objects/SlideObjectResponseObject.ts
  backend/src/shared/interfaces/response-objects/SlideResponseObject.ts
  backend/src/shared/interfaces/response-objects/UserResponseObject.ts
Labels: backend, feature

#68 docs(auth)[OK-117] Complete Swagger docs - Revert
  backend/src/modules/auth/auth.controller.ts
  backend/src/shared/interfaces/AuthToken.ts
Labels: documentation, backend

#70 refactor(modules)[OK-124] Put in order messy module code
  backend/package.json
  backend/src/main.ts
  backend/src/modules/auth/auth.controller.ts
  backend/src/modules/auth/auth.service.ts
  backend/src/modules/boards/boards.controller.ts
  backend/src/modules/boards/boards.service.ts
  backend/src/modules/slide-objects/slide-objects.service.ts
  backend/src/modules/slides/slides.controller.ts
  backend/src/modules/slides/slides.service.ts
  backend/src/modules/users/users.service.ts
  backend/src/schemas/board.schema.ts
  backend/src/shared/interfaces/response-objects/BoardResponseObject.ts
Labels: backend

#72 feat(board-permissions)[OK-126] Add board permition verification methods
  server/package-lock.json
  server/src/enums/board.permission.ts
  server/src/modules/auth/auth.controller.ts
  server/src/modules/auth/auth.service.ts
  server/src/modules/auth/decorators/users.decorator.ts
  server/src/modules/auth/guards/jwt.auth.guard.ts
  server/src/modules/auth/strategies/google.strategy.ts
  server/src/modules/auth/strategies/jwt.strategy.ts
  server/src/modules/auth/strategies/local.strategy.ts
  server/src/modules/boards/boards.service.ts
  server/src/modules/slide-objects/slide-objects.dto.ts
  server/src/modules/slide-objects/slide-objects.module.ts
  server/src/modules/slide-objects/slide-objects.service.ts
  server/src/modules/slides/slides.service.ts
  server/src/schemas/board.schema.ts
  server/src/schemas/slide-object.schema.ts
  server/src/shared/interfaces/Permissions.ts
  server/src/shared/interfaces/auth/AuthToken.ts
  server/src/shared/interfaces/auth/GoogleUser.ts
  server/src/shared/interfaces/auth/Payload.ts
  server/src/shared/interfaces/auth/SafeUserDoc.ts
  server/src/shared/interfaces/fabric-js/SlideObjectFilter.ts
  server/src/shared/interfaces/fabric-js/SlideObjectPath.ts
  server/src/shared/interfaces/fabric-js/SlideObjectShadow.ts
  server/src/shared/interfaces/fabric-js/SlideObjectTextStyles.ts
  server/src/shared/interfaces/response-objects/SlideObjectResponseObject.ts
Labels: backend, feature

#74 feat(navigation)[OK-134] Add basic navigation for navbar and /user-boards
  client/src/components/Header.tsx
  client/src/components/HeaderLinks.tsx
  client/src/components/UserBoardsActionButtons.tsx
  client/src/components/board/HorizontalMenu.tsx
Labels: frontend

#76 fix(permissions)[OK-139] Correct types for permissions to work
  server/src/modules/boards/boards.service.ts
Labels: fix, backend

#77 chore(deps)[OK-141] Fix Dependabot security alerts
  client/package-lock.json
  client/package.json
  server/package-lock.json
  server/package.json
Labels: technical, frontend, backend

#78 fix(default slide)[OK-142] Add slide creation when board is created
  server/src/schemas/board.schema.ts
Labels: fix, backend

#83 fix(slide-object-service)[OK-153] Fix slide-object deletion bug
  server/src/modules/slide-objects/slide-objects.service.ts
Labels: fix, backend

#82 feat(ws)[OK-129] Add base impl of ws with auth
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/enums/board.permission.ts
  server/src/gateway/gateway.dto.ts
  server/src/gateway/gateway.module.ts
  server/src/gateway/gateway.ts
  server/src/modules/auth/auth.module.ts
  server/src/modules/auth/auth.service.ts
  server/src/modules/auth/decorators/ws.client.decorator.ts
  server/src/modules/auth/guards/ws.auth.guard.ts
  server/src/modules/auth/strategies/ws.strategy.ts
  server/src/modules/boards/boards.controller.ts
  server/src/modules/boards/boards.service.ts
  server/src/modules/slides/slides.service.ts
  server/src/modules/users/users.service.ts
  server/src/shared/interfaces/AvailableBoards.ts
  server/src/shared/interfaces/auth/GatewaySocket.ts
Labels: backend, feature

#80 feat(Board)[OK-136] Base board API integration & Object creation integration with backend through REST API
  client/src/app/actions/boardActions.ts
  client/src/app/actions/slideActions.ts
  client/src/app/api/auth/google/route.ts
  client/src/app/board/layout.tsx
  client/src/app/user-boards/[boardId]/slides/[slideIndex]/layout.tsx
  client/src/app/user-boards/[boardId]/slides/[slideIndex]/page.tsx
  client/src/components/UserBoardsActionButtons.tsx
  client/src/contexts/AuthContext.tsx
  client/src/contexts/CanvasContext.tsx
  client/src/contexts/FileContext.tsx
  client/src/contexts/UndoRedoContext.tsx
  client/src/contexts/complexToast.tsx
  client/src/errors/ApiError.ts
  client/src/hooks/auth/useHandleAuth.ts
  client/src/hooks/board/useCanvasEventListeners.tsx
  client/src/hooks/board/useMenuActions.ts
  client/src/interfaces/canvas-context.ts
  client/src/interfaces/responses/api-error-response.ts
  client/src/interfaces/responses/board-data-response.ts
  client/src/interfaces/responses/permissions-response.ts
  client/src/interfaces/responses/slide-response.ts
  client/src/lib/toastsUtils.tsx
  client/src/utils/authApi.ts
  client/src/utils/board/fileUtils.ts
Labels: frontend, tested-ok

#81 test(users-controller)[OK-137] Add tests
  server/package-lock.json
  server/package.json
  server/src/modules/users/test/users.controller.test.ts
Labels: backend, tests

#85 feat(Slide)[OK-94] Integrate slider with backend
  client/package-lock.json
  client/package.json
  client/src/app/actions/slideActions.ts
  client/src/app/user-boards/[boardId]/slides/[slideIndex]/layout.tsx
  client/src/app/user-boards/[boardId]/slides/[slideIndex]/page.tsx
  client/src/components/board/Canvas.tsx
  client/src/components/board/Pagination.tsx
  client/src/components/board/SlideControls/DeleteSlideDialog.tsx
  client/src/components/board/SlideControls/SlideActions.tsx
  client/src/components/board/SlideControls/SlideControls.tsx
  client/src/components/board/SlideControls/SlidePagination.tsx
  client/src/components/ui/dialog.tsx
  client/src/components/ui/hover-card.tsx
  client/src/contexts/SlideControlsContext.tsx
  client/src/interfaces/responses/slide-id-response.ts
Labels: frontend, test-required

#87 feat(ws)[OK-158] Add object action handler
  server/src/enums/object.action.ts
  server/src/gateway/gateway.dto.ts
  server/src/gateway/gateway.module.ts
  server/src/gateway/gateway.ts
  server/src/gateway/providers/connection.service.ts
  server/src/gateway/providers/join.board.service.ts
  server/src/gateway/providers/object.action.service.ts
  server/src/modules/auth/auth.service.ts
  server/src/modules/auth/guards/ws.auth.guard.ts
  server/src/modules/slide-objects/slide-objects.module.ts
  server/src/modules/slide-objects/slide-objects.service.ts
  server/src/modules/slide-objects/ws.objects.service.ts
  server/src/modules/slides/slides.service.ts
  server/src/shared/interfaces/auth/GatewaySocket.ts
  server/src/shared/interfaces/auth/GwSocket.ts
Labels: backend, feature

#84 feat(slide-object-schema)[OK-146] Add Eraser and missing fields, extract FabricJsCanvasObjectBase
  server/src/modules/slide-objects/slide-objects.dto.ts
  server/src/schemas/slide-object.schema.ts
  server/src/shared/interfaces/fabric-js/SlideObjectPath.ts
  server/src/shared/interfaces/response-objects/SlideObjectResponseObject.ts
Labels: backend, feature, refactor

#88 feat(ws)[OK-162] Add leave board handler
  server/src/gateway/gateway.ts
  server/src/gateway/providers/join.board.service.ts
  server/src/gateway/providers/object.action.service.ts
Labels: backend, feature

#90 feat(ws)[OK-165] Add guard for board permission
  server/src/gateway/gateway.ts
  server/src/gateway/providers/join.board.service.ts
  server/src/gateway/providers/object.action.service.ts
  server/src/modules/auth/decorators/permissions.decorator.ts
  server/src/modules/auth/decorators/roles.decorator.ts
  server/src/modules/auth/guards/board.permission.guard.ts
  server/src/modules/auth/guards/jwt.auth.guard.ts
  server/src/modules/auth/guards/ws.auth.guard.ts
Labels: backend, tested-ok, feature

#93 refactor(object-service)[OK-169] Refactor
  .gitignore
  server/package.json
  server/src/gateway/gateway.dto.ts
  server/src/gateway/providers/object.action.service.ts
  server/src/modules/objects/objects.dto.ts
  server/src/modules/objects/objects.service.ts
Labels: backend, test-required, refactor
